### ISSUE TITLE
Mod folder for Atmosphere has changed from Atmosphere/titles to Atmosphere/contents

### ISSUE THREAD

**Issue by MoeMonsuta** [pablo67340/BoTW-Durability-Mod#1]
The old mod folder setup was **Atmosphere/titles** which this mod still uses in the folder structure. 

However, the new setup is **Atmosphere/contents**

Also, thanks for the great mod Once I learned of this change, I started enjoying. :)

**Comment by pablo67340** [comment]
Thank you for the report! The update was posted to Gamebanana, but not here. Fixed!
